version : "3.3"
services:
    server:
        build: ./server
        ports:
            - "8000:8000"
        restart: always
        networks:
            - mern-app
        depends_on:
            - mongo
            - cache
        links:
            - "mongo:mongo"
            - "cache:cache"

    frontend:
        build: ./client
        stdin_open: true
        ports:
            - "5000:80"
        networks:
            - mern-app

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        ports:
            - 27017:27017
        volumes:
            - ./mongodb:/data/db
        networks:
            - mern-app

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
        networks: 
            - mern-app
        depends_on:
            - mongo

    scraper:
        image: python
        build: ./scraper
        restart: always
        command: uvicorn main:app --reload --host 0.0.0.0 --port 7000
        volumes: 
            - ./scraper:/usr/src/scraper
        ports:
            - 7000:7000
        networks:
            - mern-app
        links:
            - "cache:cache"
            - "mongo:mongo"
        depends_on:
            - cache

    cache:
        build: ./cache
        restart: always
        volumes:
            - ./cache:/data
        ports:
            - "6379:6379"
        networks:
            - mern-app

networks:
        mern-app:
            driver: bridge
