version : "3.3"
services:
  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - mern-app

  frontend:
    build: ./client
    stdin_open: true
    ports:
      - "5000:5000"
    networks:
      - mern-app

  mongodb:
        image: mongo:latest
        container_name: mongo
        environment: 
                MONGO_INITDB_ROOT_USERNAME: admin
                MONGO_INITDB_ROOT_PASSWORD: admin

networks:
  mern-app:
    driver: bridge
