version: "3.3"
services:
  scraper:
    image: python
    build: .
    command: uvicorn main:app --reload --host 0.0.0.0 --port 3000
    volumes: 
      - .:/usr/src/scraper
    ports:
      - 3000:3000
